[package]
name = "tracegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memsim-rs = { path = "../memsim-rs"}
rand = "0.8.5"
clap = { version = "3.2.22", features = ["derive"] }